### ISSUE TITLE
Сломаны ссылки в доке по аннотированию

### ISSUE THREAD

**Issue by CD7567** [CD7567/mipt2024f-4-common-knowledge#4]
![image](https://github.com/user-attachments/assets/e75a7844-0de7-403b-b316-a1e6a7236269)

**Comment by CD7567** [comment]
Также обрати внимание:
```
https://github.com/CD7567/mipt2024f-4-common-knowledge/blob/BarcodeClassificator/BarcodeTypes/img/region_attributes_type.png
```

Ты прикладываешь ссылки, привязанные к твоей ветке. Нужно прикладывать относительные ссылки текущей ветки, например:

```
BarcodeTypes/img/region_attributes_type.png
```

В противном случае удаление ветки сломает все картинки в документах.

**Comment by ismdnvat** [comment]
починила
